obj-y += nand.o

nand-objs += nand_interface.o \
	nfd/nand_ota_burn.o \
	nfd/boot_head/boot0_op.o \
	nfd/nand_base.o \
	nfd/nand_blk.o \
	nfd/nand_dev.o \
	nfd/nand_class.o \
	nfd/nand_osal_for_linux.o \

nand-objs += lib/src/nftl/nftl_list.o
nand-objs += lib/src/nftl/nftl_logic.o
nand-objs += lib/src/nftl/nftl_gc.o
nand-objs += lib/src/nftl/nftl_cache.o
nand-objs += lib/src/nftl/nftl_sector_cache.o
nand-objs += lib/src/nftl/nftl_common.o
nand-objs += lib/src/nftl/nftl_build.o
nand-objs += lib/src/nftl/nftl_start.o
nand-objs += lib/src/nftl/nftl_interface.o
nand-objs += lib/src/nftl_interface/nftl_init.o
nand-objs += lib/src/nftl_interface/nftl_hw_interface.o
nand-objs += lib/src/nftl_interface/nftl_uboot_interface.o
nand-objs += lib/src/physic/nand_format.o
nand-objs += lib/src/physic/nand_id.o
nand-objs += lib/src/physic/nand_phy.o
nand-objs += lib/src/physic/nand_physic_interface.o
nand-objs += lib/src/physic/nand_scan.o
nand-objs += lib/src/physic/nand_simple_r.o
nand-objs += lib/src/physic/nand_simple_w.o
nand-objs += lib/src/physic/nfc_reg.o
nand-objs += lib/src/physic/nfc_r.o
nand-objs += lib/src/physic/nfc_w.o
nand-objs += lib/src/phy/build_nand_partition.o
nand-objs += lib/src/phy/build_phy_partition.o
nand-objs += lib/src/phy/hw_phy.o
nand-objs += lib/src/phy/nand_info_init.o
nand-objs += lib/src/phy/phy_input.o
nand-objs += lib/src/phy_v2/nand_info_init_v2.o
nand-objs += lib/src/phy_v2/build_phy_partition_v2.o
