obj-$(CONFIG_SND_SUNXI_SOC_DAUDIO_INTERFACE) += sunxi-daudio.o
obj-$(CONFIG_SND_SUNXI_SOC_DAUDIO_INTERFACE) += sunxi-daudiodma.o
obj-$(CONFIG_SND_SUNXI_SOC_DAUDIO_INTERFACE) += snddaudio.o
obj-$(CONFIG_SND_SUNXI_SOC_DAUDIO_INTERFACE) += sunxi-snddaudio.o

