#!/usr/bin/env python

import smbus, time, sys

bus = smbus.SMBus(1)
address = 0x52

def dump():
    bus.write_byte(address, 0)
    time.sleep(0.1)
    res = []
    for i in xrange(256):
        time.sleep(0.001)
        res += [bus.read_byte(address)]
    for i in xrange(32):
        for v in res[i*8:(i+1)*8]:
            sys.stdout.write("{:<4}".format(v))
        print ''
    
dump()
